In [1]:
import numpy as np

In [2]:
x=[[1,2],[3,4]]
total = 0
for i in x:
    total +=sum(i)
print(total)


10


In [3]:
x.sum

AttributeError: 'list' object has no attribute 'sum'

In [ ]:
x=[[1,2],[3,4]]
nx = np.array(x)

In [6]:
(nx.sum())
print(nx.min())

NameError: name 'nx' is not defined

In [10]:
type(nx)

NameError: name 'nx' is not defined

functions to create matrix 
- arange: create a range of numbers
- linspace: create a matrix of specified number of elements
- ones : create a matrix of ones
- zeros: create a matrix of zeros
- random.randint : create a matrix of random integers
- random.rand : create a matrix of random floats
- diag : create a matrix with diagonal elements

In [11]:
a = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [14]:
np.arange(1,5,.05)

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05,
       2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 ,
       2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  , 3.05, 3.1 , 3.15,
       3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 , 3.55, 3.6 , 3.65, 3.7 ,
       3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25,
       4.3 , 4.35, 4.4 , 4.45, 4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 ,
       4.85, 4.9 , 4.95])

In [15]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.random.randint(1,100,10)

array([23, 94, 40, 33,  4, 99, 10, 51, 79, 19], dtype=int32)

In [19]:
x = [1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [21]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
x.flatten()

AttributeError: 'list' object has no attribute 'flatten'

In [25]:
y = np.arange(1,26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
a= np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[2 5 9]
 [8 1 1]
 [6 5 7]]
[[3 8 6]
 [1 4 2]
 [1 8 2]]


In [28]:
a + b

array([[ 5, 13, 15],
       [ 9,  5,  3],
       [ 7, 13,  9]], dtype=int32)

In [29]:
a.dot(b)# dot product

array([[ 20, 108,  40],
       [ 26,  76,  52],
       [ 30, 124,  60]], dtype=int32)

In [30]:
a + 10

array([[12, 15, 19],
       [18, 11, 11],
       [16, 15, 17]], dtype=int32)

In [31]:
print(a.mean())

4.888888888888889


In [32]:
print(a.mean(axis=0))

[5.33333333 3.66666667 5.66666667]


In [33]:
print(a.sum())

44


In [34]:
np.sin(a)

array([[ 0.90929743, -0.95892427,  0.41211849],
       [ 0.98935825,  0.84147098,  0.84147098],
       [-0.2794155 , -0.95892427,  0.6569866 ]])

In [36]:
print(np.cos(a))
print(np.tan(a))

[[-0.41614684  0.28366219 -0.91113026]
 [-0.14550003  0.54030231  0.54030231]
 [ 0.96017029  0.28366219  0.75390225]]
[[-2.18503986 -3.38051501 -0.45231566]
 [-6.79971146  1.55740772  1.55740772]
 [-0.29100619 -3.38051501  0.87144798]]


In [37]:
print(np.sin(a))

[[ 0.90929743 -0.95892427  0.41211849]
 [ 0.98935825  0.84147098  0.84147098]
 [-0.2794155  -0.95892427  0.6569866 ]]


-slicing
  - 1D - arr[start:stop]
  - 2D

In [2]:
import numpy as np

In [5]:
x = np.linspace(1,100,25).reshape(5,5).astype(int)
print(x)
print(x[0]) #row index 0
print(x[-1]) #last row
print(x[2])
print(x[:3])
print(x[-2:])

print(x[:,0])
print(x[:,-1])
print(x[2:4,2:])


[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]
[[ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1 21 42 62 83]
[ 17  38  58  79 100]
[[50 54 58]
 [71 75 79]]


filtering


In [6]:
x > 50 #boolean filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
x[x>50]

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [8]:
x

array([[  1,   5,   9,  13,  17],
       [ 21,  25,  29,  34,  38],
       [ 42,  46,  50,  54,  58],
       [ 62,  67,  71,  75,  79],
       [ 83,  87,  91,  95, 100]])

In [10]:
x[x % 2 == 0]

array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])